# PowerPC emulator configuration

TARGET_COMPRESS_MODULE_SYMBOLS := false
TARGET_PRELINK_MODULE := false
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_PROVIDES_INIT_RC := true
TARGET_NO_RADIOIMAGE := true
USE_CAMERA_STUB := true
#BOARD_USES_ALSA_AUDIO := true
#BUILD_WITH_ALSA_UTILS := true
BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_VIRTUAL_TOUCHSCREEN := true
USE_CUSTOM_RUNTIME_HEAP_MAX := "64M"

# Setup some runtime system properties.
TARGET_BOARD_PLATFORM := ppc
#TARGET_BOOTLOADER_BOARD_NAME := tbd
